### PR TITLE
Weekly PR

### PR DESCRIPTION
**Pull request by EugeneButusov**
+ Feature #143 GPGS for Profile

### CODE REVIEW

**Comment by EugeneButusov** [comment]
@borisspektor @refaelos, it's ready to merge.

**Comment by klhurley** [comment]
Another small fix just added for the build_all command that doesn't copy GameCenter to the build directory.  Might want to include that in this pull request

**Comment by EugeneButusov** [comment]
@klhurley, it works for me, all provider is copied to the build dir. I found that https://github.com/soomla/cocos2dx-profile/blob/master/development/build_ios#L18-L22 doing extra work already done here: https://github.com/soomla/cocos2dx-profile/blob/master/development/build_ios#L15-L16. Do you have the same behaviour?

**Comment by klhurley** [comment]
Hi Eugene,
Yes, you are right, didn't see the copy build/* above, so Yes, I guess that build_ios is doing extra work.

**Comment by klhurley** [comment]
Hey Eugene,

When's this going to get merged?  Been waiting on some of these fixes.

**Comment by EugeneButusov** [comment]
@klhurley, I prepared PR data, the next turn is from SOOMLA staff, I cannot merge/make release.

**Pull request merged**
